### PR TITLE
Us42 nettoyage du code

### PR DESCRIPTION
**Pull request by Gumatan**

### CODE REVIEW

**Review by TheoBoschetti — DISMISSED** [review]
ok

**Review by TheoBoschetti — DISMISSED** [review]
ok

**Review by LoicBrassart — CHANGES_REQUESTED** [review]
Your NPCMoves are stored in NPC.jsx and NPCMoves.js

**Review by TheoBoschetti — APPROVED** [review]
ok

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
