### PR TITLE
Us#25 creation of house map

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by TheoBoschetti — DISMISSED** [review]
ok

**Review by TheoBoschetti — DISMISSED** [review]
ok

**Review by TheoBoschetti — DISMISSED** [review]
ok

**Review by LoicBrassart — COMMENTED** [review]
SnE

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by TheoBoschetti — DISMISSED** [review]
ok

**Review by TheoBoschetti — DISMISSED** [review]
ok

**Review by TheoBoschetti — APPROVED** [review]
ok

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
